name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2  # Latest version as of 2025
      with:
        node-version: '20'
        cache: 'npm'  # Enables built-in caching (preferred over manual caching)

    - name: Install dependencies
      run: npm ci
      env:
        CI: true

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Build
      run: npm run build
      env:
        CI: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.1  # Latest stable version
      with:
        name: build
        path: dist/
        retention-days: 1
